- when: mailman3_install_postgres
  block:
  - name: install postgres
    when: mailman3_install_postgres
    apt:
      name: postgresql
      state: present
      cache_valid_time: 600

  - name: verify postgres is started
    service:
      name: postgresql
      state: started
